/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package academicguidancehubgui;

import academicguidancehub.FileReaderUtils;
import academicguidancehub.FileLocationInterface;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author New HP
 */
public class AdminAllotPMroleToLecturer extends javax.swing.JFrame {

    /**
     * Creates new form AdminAllotPMroleToLecturer
     */
    public AdminAllotPMroleToLecturer() {
        initComponents();
        setSize(910, 640);
        setResizable(false);
        
        lecturerTableContent();
        projectManagerTableContent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lecturerTable = new javax.swing.JTable();
        allotBt = new javax.swing.JButton();
        cancelBt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        projectManagerTb = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Allot Project Manager Role to Lecturer Page");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(204, 204, 204))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Project Manager:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));

        lecturerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        lecturerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lecturerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lecturerTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 640, 160));

        allotBt.setBackground(new java.awt.Color(255, 51, 51));
        allotBt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        allotBt.setForeground(new java.awt.Color(255, 255, 255));
        allotBt.setText("Allot");
        allotBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allotBtMouseClicked(evt);
            }
        });
        getContentPane().add(allotBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 100, 40));

        cancelBt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelBt.setText("Cancel");
        cancelBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtMouseClicked(evt);
            }
        });
        getContentPane().add(cancelBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 550, 100, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/AllotPMRole.png"))); // NOI18N
        jLabel2.setText("AllotPMRole.png");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 180, 520));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("Allot to ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("|");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 30, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Lecturer Available:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        projectManagerTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        projectManagerTb.setEnabled(false);
        jScrollPane2.setViewportView(projectManagerTb);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 640, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtMouseClicked
        this.dispose();
        AdminDashboard obj = new AdminDashboard();
        obj.setVisible(true);
    }//GEN-LAST:event_cancelBtMouseClicked

    private void lecturerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lecturerTableMouseClicked
        
    }//GEN-LAST:event_lecturerTableMouseClicked

    private void allotBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allotBtMouseClicked
        DefaultTableModel lecturerList = (DefaultTableModel)lecturerTable.getModel();
        int selectedRow = lecturerTable.getSelectedRow();
        
        if (selectedRow != -1) {
            String id = lecturerList.getValueAt(selectedRow,0).toString();
            String name = lecturerList.getValueAt(selectedRow, 1).toString();
            String password = lecturerList.getValueAt(selectedRow, 2).toString();
            String email = lecturerList.getValueAt(selectedRow, 3).toString();
            String contact = lecturerList.getValueAt(selectedRow, 4).toString();
            String field = lecturerList.getValueAt(selectedRow, 6).toString();
            
            String delimiter = ";";
            UpdateLecturerFile(FileLocationInterface.lecturerFilePath, id, delimiter);
            UpdatePMFile(FileLocationInterface.projectManagerPath,delimiter,id,name,password,email,contact,field);
            JOptionPane.showMessageDialog(null, "Allot successfully!", "ALLOT PROJECT MANAGER SUCCESS", JOptionPane.INFORMATION_MESSAGE);
            
            lecturerTableContent();
            projectManagerTableContent();
        } else{
            JOptionPane.showMessageDialog(this, "Please select a lecturer from lecturer available table.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_allotBtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAllotPMroleToLecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAllotPMroleToLecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAllotPMroleToLecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAllotPMroleToLecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAllotPMroleToLecturer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allotBt;
    private javax.swing.JButton cancelBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable lecturerTable;
    private javax.swing.JTable projectManagerTb;
    // End of variables declaration//GEN-END:variables

    private void lecturerTableContent() {
        String delimiter = ";";
        int[] classTypeColumnIndices = {0, 1, 2, 3, 4, 5, 6};
        String[][] classTypeData = FileReaderUtils.readData(FileLocationInterface.lecturerFilePath, delimiter, classTypeColumnIndices);

        if (classTypeData != null) {
            DefaultTableModel classTypeTableModel = new DefaultTableModel();
            classTypeTableModel.addColumn("Lecturer ID");
            classTypeTableModel.addColumn("Lecturer Name");
            classTypeTableModel.addColumn("Lecturer Password");
            classTypeTableModel.addColumn("Lecturer Email");
            classTypeTableModel.addColumn("Lecturer Contact");
            classTypeTableModel.addColumn("Role");
            classTypeTableModel.addColumn("Lecturer Functional Area(s)");

            for (String[] row : classTypeData) {
                classTypeTableModel.addRow(row);
            }

            lecturerTable.setModel(classTypeTableModel);
        }
    }

    private void projectManagerTableContent() {
        String delimiter = ";";
        int[] classTypeColumnIndices = {0, 1, 2, 3, 4, 5, 6};
        String[][] classTypeData = FileReaderUtils.readData(FileLocationInterface.projectManagerPath, delimiter, classTypeColumnIndices);

        if (classTypeData != null) {
            DefaultTableModel classTypeTableModel = new DefaultTableModel();
            classTypeTableModel.addColumn("PM ID");
            classTypeTableModel.addColumn("PM Name");
            classTypeTableModel.addColumn("PM Password");
            classTypeTableModel.addColumn("PM Email");
            classTypeTableModel.addColumn("PM Contact");
            classTypeTableModel.addColumn("Role");
            classTypeTableModel.addColumn("PM Functional Area(s)");

            for (String[] row : classTypeData) {
                classTypeTableModel.addRow(row);
            }

            projectManagerTb.setModel(classTypeTableModel);
        }
    }

    private void UpdateLecturerFile(String studentfilePath, String id, String delimiter) {
        try {
            // Read the content of the file and store it in a list
            File file = new File(studentfilePath);
            BufferedReader reader = new BufferedReader(new FileReader(file));
            String line;
            StringBuilder content = new StringBuilder();
            while ((line = reader.readLine()) != null) {
                // Split the line by the delimiter to check if it contains the specified 'tp'
                String[] parts = line.split(delimiter);
                if (!parts[0].equals(id)) { // If the 'tp' doesn't match, keep the line
                    content.append(line).append(System.lineSeparator());
                }
            }
            reader.close();

            // Write the updated content back to the file
            BufferedWriter writer = new BufferedWriter(new FileWriter(file));
            writer.write(content.toString());
            writer.close();

            System.out.println("Entry with tp '" + id + "' removed from the file.");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void UpdatePMFile(String pmfilePath, String delimiter, String id, String name, String password, String email, String contact, String field) {
        String role = "Project Manager";
        
        String pmRecord = id + ";" + name + ";" + password + ";" + email + ";" + contact + ";" + role + ";" + field;
        
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(pmfilePath, true))) {
            writer.write(pmRecord);
            writer.newLine();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
