/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package academicguidancehubgui;

import academicguidancehub.Lecturer;
import academicguidancehub.Presentation;

/**
 *
 * @author User
 */
public class LecturerDashboard extends javax.swing.JFrame {

    Lecturer lc = null;

    public LecturerDashboard(Lecturer lc) {
        initComponents();
        this.lc = lc;
        lblusername.setText("Lecturer: " + lc.getName());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomePage = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ViewAssignSup = new javax.swing.JLabel();
        ViewSuperviseeList = new javax.swing.JLabel();
        ViewPendingReport = new javax.swing.JLabel();
        Presentation = new javax.swing.JLabel();
        HomePage1 = new javax.swing.JButton();
        CompletedReports = new javax.swing.JLabel();
        PresentationReq = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PendingReportNo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PresentationRequestNo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ReportCompletedNo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        HomePage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Home.png"))); // NOI18N
        HomePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomePageMouseClicked(evt);
            }
        });
        HomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePageActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        ViewAssignSup.setText("View Assign supervisee");
        ViewAssignSup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewAssignSupMouseClicked(evt);
            }
        });

        ViewSuperviseeList.setText("View Supervisee List");
        ViewSuperviseeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewSuperviseeListMouseClicked(evt);
            }
        });

        ViewPendingReport.setText("View Pending Report");
        ViewPendingReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewPendingReportMouseClicked(evt);
            }
        });

        Presentation.setText("View Presentation Request");
        Presentation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PresentationMouseClicked(evt);
            }
        });

        HomePage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Home.png"))); // NOI18N
        HomePage1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomePage1MouseClicked(evt);
            }
        });
        HomePage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePage1ActionPerformed(evt);
            }
        });

        CompletedReports.setText("View Completed Reports");
        CompletedReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CompletedReportsMouseClicked(evt);
            }
        });

        PresentationReq.setText("View Presentation Date");
        PresentationReq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PresentationReqMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(HomePage1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PresentationReq)
                    .addComponent(CompletedReports)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ViewPendingReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewAssignSup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewSuperviseeList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Presentation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomePage1)
                .addGap(18, 18, 18)
                .addComponent(ViewAssignSup, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ViewSuperviseeList, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(ViewPendingReport, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Presentation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PresentationReq, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CompletedReports, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        lblusername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Welcome back");

        javax.swing.GroupLayout PendingReportNoLayout = new javax.swing.GroupLayout(PendingReportNo);
        PendingReportNo.setLayout(PendingReportNoLayout);
        PendingReportNoLayout.setHorizontalGroup(
            PendingReportNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        PendingReportNoLayout.setVerticalGroup(
            PendingReportNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Pending Report");

        javax.swing.GroupLayout PresentationRequestNoLayout = new javax.swing.GroupLayout(PresentationRequestNo);
        PresentationRequestNo.setLayout(PresentationRequestNoLayout);
        PresentationRequestNoLayout.setHorizontalGroup(
            PresentationRequestNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
        );
        PresentationRequestNoLayout.setVerticalGroup(
            PresentationRequestNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Presentation Request");

        javax.swing.GroupLayout ReportCompletedNoLayout = new javax.swing.GroupLayout(ReportCompletedNo);
        ReportCompletedNo.setLayout(ReportCompletedNoLayout);
        ReportCompletedNoLayout.setHorizontalGroup(
            ReportCompletedNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );
        ReportCompletedNoLayout.setVerticalGroup(
            ReportCompletedNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Reports Completed");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblusername, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PendingReportNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(210, 210, 210)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PresentationRequestNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(167, 167, 167)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(ReportCompletedNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblusername, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ReportCompletedNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PresentationRequestNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PendingReportNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewAssignSupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewAssignSupMouseClicked
        LecturerViewAssignedSupervisees viewAssignedSupervisees = new LecturerViewAssignedSupervisees(lc);
        viewAssignedSupervisees.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ViewAssignSupMouseClicked

    private void ViewSuperviseeListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewSuperviseeListMouseClicked
        String selectedLecturerId = lc.getUserId();
        LecturerViewSuperviseeList superviseeListFrame = new LecturerViewSuperviseeList(lc, selectedLecturerId);
        superviseeListFrame.setVisible(true);
    this.setVisible(false);      this.setVisible(false);      }//GEN-LAST:event_ViewSuperviseeListMouseClicked

    private void PresentationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PresentationMouseClicked
        LecturerConfirmDateOfPresentation LCDOP = new LecturerConfirmDateOfPresentation(lc);
        LCDOP.setVisible(true);
        this.dispose();    }//GEN-LAST:event_PresentationMouseClicked

    private void HomePageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePageMouseClicked
        LecturerDashboard lecturerHomePage = new LecturerDashboard(lc);
        this.setVisible(false);
        lecturerHomePage.setVisible(true);
    }//GEN-LAST:event_HomePageMouseClicked

    private void HomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomePageActionPerformed

    private void HomePage1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePage1MouseClicked
        LecturerDashboard lecturerHomePage = new LecturerDashboard(lc);
        this.setVisible(false);
        lecturerHomePage.setVisible(true);
    }//GEN-LAST:event_HomePage1MouseClicked

    private void HomePage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePage1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomePage1ActionPerformed

    private void ViewPendingReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewPendingReportMouseClicked
        LecturerViewPendingReport LVPR = new LecturerViewPendingReport(lc);
        this.setVisible(false);
        LVPR.setVisible(true);
    }//GEN-LAST:event_ViewPendingReportMouseClicked

    private void PresentationReqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PresentationReqMouseClicked
        LecturerviewPresentationDate LVPD = new LecturerviewPresentationDate(lc);
        this.setVisible(false);
        LVPD.setVisible(true);
    }//GEN-LAST:event_PresentationReqMouseClicked

    private void CompletedReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompletedReportsMouseClicked
        LecturerViewCompletedReports LVCR = new LecturerViewCompletedReports(lc);
        this.setVisible(false);
        LVCR.setVisible(true);
    }//GEN-LAST:event_CompletedReportsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CompletedReports;
    private javax.swing.JButton HomePage;
    private javax.swing.JButton HomePage1;
    private javax.swing.JPanel PendingReportNo;
    private javax.swing.JLabel Presentation;
    private javax.swing.JLabel PresentationReq;
    private javax.swing.JPanel PresentationRequestNo;
    private javax.swing.JPanel ReportCompletedNo;
    private javax.swing.JLabel ViewAssignSup;
    private javax.swing.JLabel ViewPendingReport;
    private javax.swing.JLabel ViewSuperviseeList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblusername;
    // End of variables declaration//GEN-END:variables
}
